/**=====================================================================
 * Appirio, Inc
 * Test Class Name: {{ api_name }}
 * Class Name: [Class name for which test class created]
 * Description: [Task # with multi-line description here]
 * Created Date: [MM/DD/YYYY]
 * Created By: [FirstName LastName] (Appirio)
 * 
 * Date Modified                Modified By                  Description of the update
 * [MON DD, YYYY]             	[FirstName LastName]		 [Short description for changes]
 =====================================================================*/
@isTest
private class {{ api_name }} {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
    }
}