/**=====================================================================
 * Appirio, Inc
 * URL Rewriter: {{ api_name }}
 * Description: [Task# with multi-line description here]
 * Created Date: [MM/DD/YYYY]
 * Created By: [FirstName LastName] (Appirio)
 * 
 * Date Modified                Modified By                  Description of the update
 * [MON DD, YYYY]             	[FirstName LastName]		 [Short description for changes]
 =====================================================================*/
global class {{ api_name }} implements Site.UrlRewriter {
	
	global PageReference mapRequestUrl(PageReference yourFriendlyUrl) {
		
		return null;
	}
	
	global List<PageReference> generateUrlFor(List<PageReference> yourSalesforceUrls) {
		
		return null;
	}
	
}